### ISSUE TITLE
Clarification on Passing the Features into BipartiteGraphConvolution

### ISSUE THREAD

**Issue by srikesh-07** [MIRALab-USTC/L2O-G2MILP#2]
Hello Authors @zijiegeng and @ziao-guo ,

First of all, I would like to thank the authors for their great research and publication.

I am going through the code and I give my appreciation to the authors as the code is well organized and developed well. I doubt L211 of `nn.py` (Also attached the piece of code for easy understanding)

So, According to the code in L208 `constraint_features embeddings` is obtained by passing the `input constraint_features` and `input variable_features`. But in Line 211, You can see the obtained `constraint_features embeddings` from the `BipartiteGraphConvolution`  is passed with the input `input variable_features` to get the `variable_features embeddings`.

My doubt is, Is there any specific reason, Why the `input constraint_features` is not passed with `input variable_features`  into `BipartiteGraphConvolution` to obtain the `variable_features embeddings` ? 

i.e) Making a copy of `constraint_features` to another variable before passing it to `self.conv_v_to_c_layers[i]` and passing the copied `constraint_features` into ` self.conv_c_to_v_layers[i]`.

Looking forward to your insights.

Thank you

[Code Reference](https://github.com/MIRALab-USTC/L2O-G2MILP/blob/5d0e442d88763fa5c38f6162114714e8ebf4b2b6/src/nn.py#L207C1-L213C14)

**Comment by zijiegeng** [comment]
Hi,

Thank you for your interests in our work. My consideration is that the `constraint_features` contain information of the variables in this passing, but the `input constraint_features` does not.

For example, consider a bipartite graph below. In the first message passing, first `c1` aggregates information from `x1` and `x2`. If we pass `constraint_features` to obtain `variable_features`, then the information about `x2` can be passed to `x1` in this message passing. While if we use `input constraint_features' instead, this information will be passed in the next message passing layer.
```
x1      x2
  \    /
    c1
```
