### ISSUE TITLE
Doubts With Reproducing the Results

### ISSUE THREAD

**Issue by srikesh-07** [MIRALab-USTC/L2O-G2MILP#5]
Hello Authors @zijiegeng and @ziao-guo ,

First of all, I would like to thank the authors for their great research and publication.

I have tried to reproduce the results published in the literature. First of all, I tried with the `MIK` dataset. I **have used the split that authors have shared in Google Drive.** 

I have followed `README` and preprocessed the dataset. I have trained it and was able to get the **following similarity scores which is actually lesser,**

1. **Dataset:** `MIK`
2. **ETA-0.01:**  `0.97`
3. **ETA-0.05:**  `0.94`
4. **ETA-0.1:**  `0.90`

Regarding my environment details, I created the same environment as the authors suggested and ran the experiment on the RTX 3090.

I request the authors to guide me on the following doubts,
1. Should I change any configuration to obtain the results in the literature ?
2. Can you please confirm that I am using the correct train/test split of MIK dataset?

Thank you

**Comment by zijiegeng** [comment]
Hi,

Thank you for your interests in our work. Thanks to the contributors, there have been two updates on the code recently.
1. @ziao-guo fixed the modularity computation error in benchmarking. [link](https://github.com/MIRALab-USTC/L2O-G2MILP/pull/1)
2. @haoyangliu123 fixed the tensor bug in generation.[link](https://github.com/MIRALab-USTC/L2O-G2MILP/pull/4)

These updates may lead to slight differences between the results and that reported in the paper. I have rerun the updated code, and the training log is attached: [train.log](https://github.com/MIRALab-USTC/L2O-G2MILP/files/14338989/train.log). You can compare the results with the log. I will rerun the code for other datasets and update the test results soon.

Regarding the train/test aplit, we use the same split with that I share in Google Drive. The datasets are too large to upoad to github, so for confirmation, I list the test instances as follows, and the others are used as the training set. Notice that the generation task only involves the training set, and the train/test split should not influence the results very significantly. I also upload the pretrained model under `models/mik/model`.

```
test set:
mik.250-5-50.1
mik.250-5-100.2
mik.250-10-75.5
mik.250-20-75.1
mik.500-10-50.3
mik.500-10-75.2
mik.500-10-75.3
mik.500-20-50.1
mik.500-20-50.4
mik.500-20-75.2
```

**Comment by zijiegeng** [comment]
@srikesh-07 Hi,

Do you have any more questions? I hope my responces could be helpful to you.

**Comment by srikesh-07** [comment]
Hello Author @zijiegeng ,

I am delighted with the solutions and suggestions you gave me right now. I will let you know if I have any questions in the future.

Thank You so much for Support !!!
