### ISSUE TITLE
Code for the Nurse Scheduling Dataset

### ISSUE THREAD

**Issue by ssakhavi** [MIRALab-USTC/L2O-G2MILP#6]
Hi, 

Your paper and repo is amazing!

Are you considering releasing the code for the "Nurse Scheduling" dataset as well? I noticed that you haven't included it inside the repo.

**Comment by zijiegeng** [comment]
Hi, Thank you for your interests and sorry for the late (as I was recently working on another job and missed the issue).

I have updated the code and sincerely hope it helps.
